#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["qrcode==8.2"]
# ///
"""Generate the QR images for one app's activity links, deterministically (Track B B2, TB-D4 (a)).

    uv run ops/app_links/gen_app_qr.py \\
        --links contracts/app_links/terakidz.v1.json \\
        --out templates/terakidz-box-insert/assets            # write
    ... --check                                               # verify, exit 1 on drift

For every activity id in the `app_links.v1` file it writes `qr-<id>.png`, a QR symbol encoding
exactly `<base>/a/<id>`, and one `own-work.json`: the licence evidence the box insert's
image assets are registered with (licence `own-work` -> factory.asset `owned`, the author note,
each file's sha256 and link). The insert places each image by its key `asset:image-qr-<app>-<id>`
because template.v1 has no QR element.

Deterministic on purpose: the same links file gives the same bytes on any machine. `qrcode`
(pinned) only computes the module matrix; the PNG is written here with the standard library as
a 1-bit greyscale image whose zlib stream uses STORED (uncompressed) deflate blocks, so no zlib
or Pillow version can change a byte. No timestamp or metadata chunk is written.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import sys
import zlib
from pathlib import Path

QRCODE_VERSION = "8.2"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
SCALE = 10  # pixels per module
BORDER = 4  # quiet-zone modules (the QR standard's minimum)
APP_RE = re.compile(r"^[a-z][a-z0-9-]{1,31}$")
BASE_RE = re.compile(r"^https://[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$")
ACTIVITY_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")
MANIFEST = "own-work.json"
GENERATOR = "ops/app_links/gen_app_qr.py"
AUTHOR_NOTE = (
    "Own work. Each image is a QR symbol generated by {generator} (qrcode {version}, "
    "error correction M) from {source}; it encodes only its activity link. No third-party "
    "artwork, font or logo is used. Made by the brand's own team through the committed "
    "generator; the commit that last changed this file dates it."
)


class LinksError(ValueError):
    """The links file is not one this generator will print (named reason)."""


# ------------------------------------------------------------------ contract


def check_links(payload: dict) -> dict:
    """The generator's own copy of the contract rules a printed link depends on."""
    if not isinstance(payload, dict) or not APP_RE.match(str(payload.get("app", ""))):
        raise LinksError("`app` must be a lowercase slug")
    base = str(payload.get("base", ""))
    if not BASE_RE.match(base):
        raise LinksError("`base` must be https://<host> with no path, port, query or trailing slash")
    status = payload.get("base_status")
    if status == "placeholder" and not base.endswith(".test"):
        raise LinksError("a placeholder `base` must be a .test host")
    if status == "confirmed" and base.endswith(".test"):
        raise LinksError("a confirmed `base` cannot be a .test host")
    if status not in ("placeholder", "confirmed"):
        raise LinksError("`base_status` must be placeholder or confirmed")
    activities = payload.get("activities")
    if not isinstance(activities, list) or not activities:
        raise LinksError("`activities` must list at least one id")
    if len(set(activities)) != len(activities):
        raise LinksError("`activities` repeats an id")
    for activity in activities:
        if not isinstance(activity, str) or not ACTIVITY_RE.match(activity):
            raise LinksError("an activity id is not a lowercase slug")
    return payload


def link_for(payload: dict, activity: str) -> str:
    return f"{payload['base']}/a/{activity}"


def asset_key(payload: dict, activity: str) -> str:
    return f"image-qr-{payload['app']}-{activity}"


def file_name(activity: str) -> str:
    return f"qr-{activity}.png"


# ------------------------------------------------------------------ PNG


def stored_zlib(data: bytes) -> bytes:
    """A zlib stream of STORED deflate blocks: byte-identical under every zlib implementation."""
    out = bytearray(b"\x78\x01")
    blocks = [data[i : i + 65535] for i in range(0, len(data), 65535)] or [b""]
    for index, block in enumerate(blocks):
        final = 1 if index == len(blocks) - 1 else 0
        out += bytes([final]) + struct.pack("<HH", len(block), len(block) ^ 0xFFFF) + block
    out += struct.pack(">I", zlib.adler32(data))
    return bytes(out)


def _chunk(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body)) + kind + body + struct.pack(">I", zlib.crc32(kind + body))


def png_bytes(matrix: list[list[bool]], scale: int = SCALE) -> bytes:
    """A 1-bit greyscale PNG of a square module matrix (True = dark), `scale` px per module."""
    size = len(matrix)
    if not size or any(len(row) != size for row in matrix):
        raise ValueError("the module matrix must be square and non-empty")
    width = size * scale
    raw = bytearray()
    for row in matrix:
        bits = []
        for dark in row:
            bits.extend([0 if dark else 1] * scale)
        packed = bytearray()
        for start in range(0, width, 8):
            byte = 0
            for offset, bit in enumerate(bits[start : start + 8]):
                byte |= bit << (7 - offset)
            packed.append(byte)
        line = b"\x00" + bytes(packed)  # filter type 0 (None)
        raw += line * scale
    header = struct.pack(">IIBBBBB", width, width, 1, 0, 0, 0, 0)
    return PNG_SIGNATURE + _chunk(b"IHDR", header) + _chunk(b"IDAT", stored_zlib(bytes(raw))) + _chunk(b"IEND", b"")


def qr_matrix(text: str) -> list[list[bool]]:
    import qrcode  # noqa: PLC0415 - the only non-stdlib dependency, needed for generation only
    from qrcode.constants import ERROR_CORRECT_M  # noqa: PLC0415

    code = qrcode.QRCode(version=None, error_correction=ERROR_CORRECT_M, box_size=1, border=BORDER)
    code.add_data(text)
    code.make(fit=True)
    return [[bool(cell) for cell in row] for row in code.get_matrix()]


# ------------------------------------------------------------------ build


def manifest_text(payload: dict, source: str, files: dict[str, bytes]) -> str:
    manifest = {
        "licence": "own-work",
        "licence_type": "owned",
        "commercial_use": True,
        "author_note": AUTHOR_NOTE.format(generator=GENERATOR, version=QRCODE_VERSION, source=source),
        "generator": GENERATOR,
        "generator_deps": {"qrcode": QRCODE_VERSION},
        "source": source,
        "assets": [
            {
                "activity": activity,
                "key": asset_key(payload, activity),
                "kind": "image",
                "file": file_name(activity),
                "link": link_for(payload, activity),
                "sha256": hashlib.sha256(files[file_name(activity)]).hexdigest(),
            }
            for activity in payload["activities"]
        ],
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def build(payload: dict, source: str) -> dict[str, bytes]:
    """Every file the output directory must hold, by name."""
    check_links(payload)
    files = {
        file_name(activity): png_bytes(qr_matrix(link_for(payload, activity))) for activity in payload["activities"]
    }
    files[MANIFEST] = manifest_text(payload, source, files).encode("utf-8")
    return files


def _source_label(links_path: Path) -> str:
    """The links file as a repo-relative path when it lives in this checkout, else its name."""
    repo = Path(__file__).resolve().parents[2]
    try:
        return links_path.resolve().relative_to(repo).as_posix()
    except ValueError:
        return links_path.name


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--links", required=True, type=Path, help="an app_links.v1 JSON file")
    parser.add_argument("--out", required=True, type=Path, help="the directory the images live in")
    parser.add_argument("--check", action="store_true", help="verify the directory; exit 1 on any drift")
    args = parser.parse_args(argv)
    try:
        payload = json.loads(args.links.read_text(encoding="utf-8"))
        files = build(payload, _source_label(args.links))
    except (OSError, ValueError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2
    if args.check:
        on_disk = {path.name: path.read_bytes() for path in args.out.iterdir()} if args.out.is_dir() else {}
        drift = sorted(name for name in files if on_disk.get(name) != files[name])
        stray = sorted(set(on_disk) - set(files))
        for name in drift:
            print(f"DRIFT: {name} differs from a fresh regeneration", file=sys.stderr)
        for name in stray:
            print(f"STRAY: {name} is not generated from the links file", file=sys.stderr)
        return 1 if drift or stray else 0
    args.out.mkdir(parents=True, exist_ok=True)
    for name, data in sorted(files.items()):
        (args.out / name).write_bytes(data)
    print(f"wrote {len(files)} files to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
