http:
  routers:
    tpp-gatus-browser:
      entryPoints:
      - websecure
      tls:
        certResolver: letsencrypt
      rule: Host(`gatus.idtpp.com`)
      priority: 100
      service: tpp-gatus-backend
      middlewares:
      - tpp-gatus-sso
      - tpp-gatus-upstream-basic
    tpp-gatus-machine-api:
      entryPoints:
      - websecure
      tls:
        certResolver: letsencrypt
      rule: Host(`gatus.idtpp.com`) && PathPrefix(`/api/v1/`) && HeaderRegexp(`Authorization`,
        `^Basic [A-Za-z0-9+/]+=*$`)
      priority: 300
      service: tpp-gatus-backend
    tpp-gatus-outpost:
      entryPoints:
      - websecure
      tls:
        certResolver: letsencrypt
      rule: Host(`gatus.idtpp.com`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 400
      service: tpp-gatus-outpost
    tpp-gatus-health:
      entryPoints:
      - websecure
      tls:
        certResolver: letsencrypt
      rule: Host(`gatus.idtpp.com`) && Path(`/health`)
      priority: 300
      service: tpp-gatus-backend
  services:
    tpp-gatus-backend:
      loadBalancer:
        servers:
        - url: http://tpp-infra-gatus:8080
    tpp-gatus-outpost:
      loadBalancer:
        servers:
        - url: https://auth.idtpp.com
  middlewares:
    tpp-gatus-sso:
      forwardAuth:
        address: https://auth.idtpp.com/outpost.goauthentik.io/auth/traefik
        trustForwardHeader: true
        authResponseHeaders:
        - X-authentik-username
        - X-authentik-email
    tpp-gatus-upstream-basic:
      headers:
        customRequestHeaders:
          Authorization: ${GATUS_UPSTREAM_AUTHORIZATION}
