#!/usr/bin/env python3
"""DEPRECATED alias: G7 has one validator, ``privacy_inventory.py``.

The former per-product B1-B12 free-text data-map format (schema ``privacy_data_map.v1``)
was retired on 2026-09-28 in favour of the single opaque-identifier v2 privacy inventory, whose
per-product documents are generated by ``privacy_documents.py`` and whose deletion tests are
executed by ``privacy_erasure.py``. This entry point is kept so existing invocations fail
loudly instead of silently: it prints a deprecation notice on stderr and delegates every argument
to the consolidated validator (which requires ``--as-of`` and a v2 inventory).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import privacy_inventory  # noqa: E402

DEPRECATION = (
    "privacy_data_map.py is deprecated: use ops/scripts/privacy_inventory.py "
    "(schema v2); the v1 data-map format is no longer accepted"
)


def main(argv: list[str] | None = None) -> int:
    print(DEPRECATION, file=sys.stderr)
    return privacy_inventory.main(argv)


if __name__ == "__main__":
    sys.exit(main())
